<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Event handling: mousemove</title>
    <script
            src="https://code.jquery.com/jquery-3.6.0.min.js"
            integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4="
            crossorigin="anonymous"></script>
</head>
<body>
    <canvas id="pad" width="480" height="320"></canvas>
    <script>
        let canvas = $('#pad')[0]
        let context = canvas.getContext("2d")
        let pendown = false

        $('#pad').mousemove(function (event) {
            let xpos = event.pageX - canvas.offsetLeft
            let ypos = event.pageY - canvas.offsetTop

            if (pendown) context.lineTo(xpos, ypos)
            else context.moveTo(xpos, ypos)
            context.stroke()
        })

        $('#pad').mousedown(function () {
            pendown = true
        })

        $('#pad').mouseup(function () {
            pendown = false
        })
    </script>
</body>
</html>